services:
  - type: web
    name: llm-document-query
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: PORT
        value: 8000
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: PINECONE_INDEX_NAME
        value: policy-index
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USERNAME
        value: neo4j
      - key: NEO4J_PASSWORD
        sync: false
      - key: NEO4J_DATABASE
        value: neo4j
      - key: GRAPHITI_ENABLED
        value: "false"
      - key: GRAPHITI_SERVER_URL
        sync: false
      - key: GRAPHITI_API_KEY
        sync: false
      - key: GRAPHITI_WORKSPACE
        value: default
      - key: GRAPHITI_EPISODE_DIR
        value: ./graphiti_episodes
